project:
  type: website
  output-dir: docs
website:
  title: "CodeVerse"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Ashil-James
      - icon: twitter
        href: https://twitter.com
      - icon: instagram
        href: https://www.instagram.com/ashil_james14?igsh=M253dzI3aGs4cXZs
format:
  html:
    theme: minty
    css: styles.css



