project:
  type: website
  output-dir: docs
website:
  title: "CodeVerse"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Ashil-James
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css



